### ISSUE TITLE
Historical depreciation did not get picked by the tool for UAL

### ISSUE THREAD

**Issue by xihan1** [erfangc/bdozer#27]
![Screen Shot 2021-04-13 at 9 28 29 AM](https://user-images.githubusercontent.com/38635487/114560350-9cf0e000-9c3a-11eb-8028-f5665029758c.png)
![Screen Shot 2021-04-13 at 9 29 05 AM](https://user-images.githubusercontent.com/38635487/114560438-b2fea080-9c3a-11eb-99f1-58b52b6ffba9.png)

**Comment by erfangc** [comment]
dammit ... UAL used a different tag in prior years ... this is really annoying 

2019
![image](https://user-images.githubusercontent.com/6001694/114713888-90828b00-9cff-11eb-804a-0520a93d378d.png)

**Comment by erfangc** [comment]
@xihan1 

so ... when we ingest facts from different Filings, we only ingest facts relevant to _that filing_

ex: Revenue for the 10K in 2020 _for_ 2020 ... if in that same 10K Revenue for 2018 is also present we ignore it ... because presumably it is available in the 10K in 2018

This is done so we don't end up with garbage data such as **last 9 month** and **last 6 month** - that way time series queries don't end up with these garbage redundant data

It seems we may need to reconsider the above ... let me know your thoughts

**Comment by xihan1** [comment]
i think the logic is fine for now unless we say a lot more firms with the same issue.
